import { AlertCircle } from "lucide-react";

interface NotUploadedMessageProps {
  type: string;
}

export const NotUploadedMessage = ({ type }: NotUploadedMessageProps) => {
  return (
    <div className="flex flex-col items-center justify-center p-8 bg-muted/30 rounded-lg border border-dashed border-muted-foreground/50 h-[300px]">
      <AlertCircle className="h-12 w-12 text-muted-foreground mb-4" />
      <h3 className="text-xl font-medium text-muted-foreground">Not Available</h3>
      <p className="text-sm text-muted-foreground/80 text-center max-w-md mt-2">
        This {type} has not been uploaded or generated by the teacher yet.
      </p>
    </div>
  );
};